# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_scene.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10game_scene.proto\x12\ngame_scene\"*\n\x06Player\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\x07Players\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05names\x18\x02 \x03(\t\"-\n\x07Matches\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\"H\n\x0cRequestState\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12$\n\x05\x63odes\x18\x02 \x03(\x0e\x32\x15.game_scene.EnumState\"\x1a\n\x04Game\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\xa2\x01\n\x08Response\x12\x16\n\x0e\x63onfirm_status\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12/\n\nstate_body\x18\x03 \x01(\x0b\x32\x19.game_scene.ResponseStateH\x00\x12/\n\nerror_body\x18\x04 \x01(\x0b\x32\x19.game_scene.ResponseErrorH\x00\x42\x08\n\x06select\"\x88\x01\n\rResponseState\x12\x0f\n\x07matches\x18\x01 \x01(\x05\x12\x0c\n\x04move\x18\x02 \x01(\t\x12\x0e\n\x06winner\x18\x03 \x01(\t\x12\x0f\n\x07players\x18\x04 \x03(\t\x12\x11\n\toutsiders\x18\x05 \x03(\t\x12$\n\x05\x63odes\x18\x06 \x03(\x0e\x32\x15.game_scene.EnumState\" \n\rResponseError\x12\x0f\n\x07\x65rr_msg\x18\x01 \x01(\t*\x8e\x01\n\tEnumState\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\r\n\tSTATE_ALL\x10\x01\x12\x11\n\rSTATE_MATCHES\x10\x02\x12\x0e\n\nSTATE_MOVE\x10\x03\x12\x10\n\x0cSTATE_WINNER\x10\x04\x12\x11\n\rSTATE_PLAYERS\x10\x05\x12\x13\n\x0fSTATE_OUTSIDERS\x10\x06\x32\x8c\x02\n\tGameScene\x12\x32\n\x05Start\x12\x13.game_scene.Players\x1a\x14.game_scene.Response\x12\x31\n\x04Move\x12\x13.game_scene.Matches\x1a\x14.game_scene.Response\x12\x31\n\x05Leave\x12\x12.game_scene.Player\x1a\x14.game_scene.Response\x12\x35\n\x03Get\x12\x18.game_scene.RequestState\x1a\x14.game_scene.Response\x12.\n\x04Stop\x12\x10.game_scene.Game\x1a\x14.game_scene.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_scene_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENUMSTATE._serialized_start=610
  _ENUMSTATE._serialized_end=752
  _PLAYER._serialized_start=32
  _PLAYER._serialized_end=74
  _PLAYERS._serialized_start=76
  _PLAYERS._serialized_end=120
  _MATCHES._serialized_start=122
  _MATCHES._serialized_end=167
  _REQUESTSTATE._serialized_start=169
  _REQUESTSTATE._serialized_end=241
  _GAME._serialized_start=243
  _GAME._serialized_end=269
  _RESPONSE._serialized_start=272
  _RESPONSE._serialized_end=434
  _RESPONSESTATE._serialized_start=437
  _RESPONSESTATE._serialized_end=573
  _RESPONSEERROR._serialized_start=575
  _RESPONSEERROR._serialized_end=607
  _GAMESCENE._serialized_start=755
  _GAMESCENE._serialized_end=1023
# @@protoc_insertion_point(module_scope)
